steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}', 
    '.'
    ]
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}']
  # Deploy container image to Cloud Run
images:
- gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}


substitutions:
    _CLOUD_RUN_SERVICE: 'uptime-checker-php-default'